### PR TITLE
Checks for discord invite link in message

### LINKED ISSUE #54: Add a filter for discord invites
Maybe some code that checks if a message starts with discord.gg/ and turn it into unusable link.

### PR DESCRIPTION
**Pull request by Assassinumz**
Fixes #54 
Added a check for discord invite link in a user's message, you can probably add more stuff in it

### CODE REVIEW

**Comment by babbaj** [comment]
🦍

**Comment by fr1kin** [comment]
🤒🤢🤮

**Comment by 0-x-2-2** [comment]
i think u got the issue wrong

**Comment by rbreslow** [comment]
🦍

**Comment by rbreslow** [comment]
🦍

**Comment by rbreslow** [comment]
🦍

**Pull request closed without merging**
